name: thinkgpt

packages:
  - ./**

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"

    dependencies:
      flutter:
        sdk: flutter


      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
      cupertino_icons: ^1.0.8
      go_router: ^14.3.0
      get_it: ^8.0.0
      injectable: ^2.5.0
      logger: ^2.4.0
      flutter_hooks: ^0.20.5
      json_annotation: ^4.9.0
      freezed_annotation: ^2.4.4
      floor: ^1.5.0
      sqflite: ^2.4.0
      flutter_svg: ^2.0.10+1
      shared_preferences: ^2.3.2
      bitsdojo_window: ^0.1.6
      flutter_bloc: ^8.1.6
      equatable: ^2.0.5
      flutter_localizations:
        sdk: flutter
      intl: any
      intl_utils: ^2.8.7

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^4.0.0
      build_runner: ^2.4.13
      injectable_generator: ^2.6.2
      freezed: ^2.5.7
      json_serializable: ^6.8.0
      floor_generator: ^1.5.0

scripts:
  gen_res:
    run: melos exec --scope="*resources*" --flutter -- "flutter pub run intl_utils:generate"

  build:shared:
    run: melos exec --scope="*shared*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  build:data:
    run: melos exec --scope="*data*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  build:domain:
    run: melos exec --scope="*domain*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  build:app:
    run: melos exec --scope="*app*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  
  
  watch:domain:
    run: melos exec --scope="*domain*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"
  watch:data:
    run: melos exec --scope="*data*"  --depends-on="build_runner" --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"
  watch:initializer:
    run: melos exec --scope="*initializer*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"
  watch:app:
    run: melos exec --scope="*app*" --depends-on="build_runner" --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"

  
  analyze:shared:
    run: melos analyze --scope="shared"
    description: Analyze shared package
  analyze:resources:
    run: melos analyze --scope="resources"
    description: Analyze resources package
  analyze:domain:
    run: melos analyze --scope="domain"
    description: Analyze domain package
  analyze:data:
    run: melos analyze --scope="data"
    description: Analyze data package
  analyze:initializer:
    run: melos analyze --scope="initializer"
    description: Analyze initializer package
  analyze:app:
    run: melos analyze --scope="app"
    description: Analyze app package
  analyze:
    run: melos analyze
    description: Analyze all packages once
    